### ISSUE TITLE
Timed out while waiting for response from server

### ISSUE THREAD

**Issue by sergiofm** [LinusU/server-accepts-email#21]
Hi there.

I'm testing your lib, but I'm always having the timed out error, even for gmail accounts.
Am I doing someting wrong?

Here's my code: 
```javascript
const serverAcceptsEmail = require('server-accepts-email');

console.log('validando email...');
serverAcceptsEmail('teste@gmail.com', {senderDomain: 'gmail.com', senderAddress: 'teste@gmail.com'}).then(result => {
  console.log("result", result);
}).catch(err => {
  console.log(err);
});
```

And here's the debug result
```bash
➜  validate-email-users DEBUG=* node index.js
validando email...
  server-accepts-email:index Resolving MX records for "gmail.com" +0ms
  server-accepts-email:index Got 5 records for "gmail.com" +49ms
  server-accepts-email:client:gmail-smtp-in.l.google.com Starting test of "teste@gmail.com" +0ms
  server-accepts-email:factory:gmail-smtp-in.l.google.com Creating connection +0ms
  server-accepts-email:socket:gmail-smtp-in.l.google.com Connecting to "gmail-smtp-in.l.google.com" +0ms
  server-accepts-email:socket:gmail-smtp-in.l.google.com Waiting for greeting +4ms
  server-accepts-email:socket:gmail-smtp-in.l.google.com Closing connection +15s
  server-accepts-email:index Error "TimeoutError: Timed out while waiting for response from server", trying next server +15s
  server-accepts-email:client:alt1.gmail-smtp-in.l.google.com Starting test of "teste@gmail.com" +0ms
  server-accepts-email:factory:alt1.gmail-smtp-in.l.google.com Creating connection +0ms
  server-accepts-email:socket:alt1.gmail-smtp-in.l.google.com Connecting to "alt1.gmail-smtp-in.l.google.com" +0ms
  server-accepts-email:socket:alt1.gmail-smtp-in.l.google.com Waiting for greeting +1ms
  server-accepts-email:socket:alt1.gmail-smtp-in.l.google.com Closing connection +15s
  server-accepts-email:index Error "TimeoutError: Timed out while waiting for response from server", trying next server +15s
  server-accepts-email:client:alt2.gmail-smtp-in.l.google.com Starting test of "teste@gmail.com" +0ms
  server-accepts-email:factory:alt2.gmail-smtp-in.l.google.com Creating connection +0ms
  server-accepts-email:socket:alt2.gmail-smtp-in.l.google.com Connecting to "alt2.gmail-smtp-in.l.google.com" +0ms
  server-accepts-email:socket:alt2.gmail-smtp-in.l.google.com Waiting for greeting +1ms
  server-accepts-email:socket:alt2.gmail-smtp-in.l.google.com Closing connection +15s
  server-accepts-email:index Error "TimeoutError: Timed out while waiting for response from server", trying next server +15s
  server-accepts-email:client:alt3.gmail-smtp-in.l.google.com Starting test of "teste@gmail.com" +0ms
  server-accepts-email:factory:alt3.gmail-smtp-in.l.google.com Creating connection +0ms
  server-accepts-email:socket:alt3.gmail-smtp-in.l.google.com Connecting to "alt3.gmail-smtp-in.l.google.com" +0ms
  server-accepts-email:socket:alt3.gmail-smtp-in.l.google.com Waiting for greeting +0ms
  server-accepts-email:socket:alt3.gmail-smtp-in.l.google.com Closing connection +15s
  server-accepts-email:index Error "TimeoutError: Timed out while waiting for response from server", trying next server +15s
  server-accepts-email:client:alt4.gmail-smtp-in.l.google.com Starting test of "teste@gmail.com" +0ms
  server-accepts-email:factory:alt4.gmail-smtp-in.l.google.com Creating connection +0ms
  server-accepts-email:socket:alt4.gmail-smtp-in.l.google.com Connecting to "alt4.gmail-smtp-in.l.google.com" +0ms
  server-accepts-email:socket:alt4.gmail-smtp-in.l.google.com Waiting for greeting +0ms
  server-accepts-email:socket:alt4.gmail-smtp-in.l.google.com Closing connection +15s
  server-accepts-email:index Error "TimeoutError: Timed out while waiting for response from server", trying next server +15s
{ TimeoutError: Timed out while waiting for response from server
    at Timeout.setTimeout [as _onTimeout] (/home/sergio/dev/mettzer/validate-email-users/node_modules/p-timeout/index.js:27:54)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) name: 'TimeoutError' }
```

**Comment by LinusU** [comment]
Most likely your ISP is blocking outgoing connections on port 25, this is quite common in order to combat spam...

Do you have the possibility to test the script on another internet connection?

**Comment by tylim88** [comment]
HI thank for the great tool

I am having timeout in digital ocean, any idea?

**Comment by LinusU** [comment]
@tylim88 http://www.lmgtfy.com/?q=digitalocean+port+25 😉

**Comment by tylim88** [comment]
ya, I already did that but still timeout

**Comment by LinusU** [comment]
closing for lack of activity
